name: Spell Check

on:
  pull_request:
    branches: [main]

jobs:
  spell-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install codespell
      run: pip install codespell

    - name: Run codespell
      run: |
        sh scripts/codespell.sh
